apiVersion: v1
kind: Service
metadata:
  name: {{ include "bashar-release.fullname" . }}-service
  labels:
    {{- include "bashar-release.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "bashar-release.labels" . | nindent 4 }}