name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: docker.io
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.USER_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: docker.io/basharsamahy/bashar:${{ github.sha }}

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        chmod 600 kubeconfig

    - name: Deploy Helm chart
      run: |
        helm upgrade --install bashar-release helm-chart --set image.repository=docker.io/basharsamahy/bashar --set image.tag=${{ github.sha }} --namespace bashar --create-namespace --kubeconfig kubeconfig
